export const ADD_ARTICLE = "ADD_ARTICLE";
export const SET_CANDIDATE = "SET_CANDIDATE";
export const DATA_LOADED = "DATA_LOADED";
export const DATA_LOADED_TO_ROGERFEDERER = "DATA_LOADED_TO_ROGERFEDERER";
